services:
  # 1. SERVICIO DE BASE DE DATOS (MYSQL)
  db:
    image: mysql:8.0
    container_name: mysql-db-cont-login
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura # ¡Cámbiala!
      MYSQL_DATABASE: db_login
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # 2. SERVICIO PHP-FPM
  php-fpm:
    build:
      context: ./php-fpm # Path del fichero Dockerfile
    container_name: php-fpm-cont-login
    volumes:
      - ./src:/var/www/html
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php-fpm/conf.d/app_conf.ini:/usr/local/etc/php/conf.d/app_conf.ini
    depends_on:
      - db

  # 3. SERVICIO WEB (NGINX)
  web:
    image: nginx:latest
    container_name: nginx-cont-login
    ports:
      - '8001:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

    # 4. SERVICIO PHPMYADMIN (¡Nuevo!)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-cont-login
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_segura # Debe coincidir con la de 'db'
    volumes:
      - my_sessions:/sessions
    ports:
      - "8080:80"
    depends_on:
      - db
# Volúmenes definidos para persistir los datos de la base de datos
volumes:
  db_data:
  my_sessions:
